### ISSUE TITLE
kubeVersion mismatch

### ISSUE THREAD

**Issue by bmetea** [pulumi/pulumi-kubernetes-cert-manager#18] opened 2023-01-13 14:36 UTC
### What happened?

Kubernetes version = 1.23.0

When I try to create resources with this package I get the following output.
```
Previewing update (xxxxxx):
     Type                                   
     pulumi:pulumi:Stack                    
 +   ├─ kubernetes:cert-manager.io/v1:Issuer
 +   ├─ kubernetes-cert-manager:index:CertMa
     └─ kubernetes:helm.sh/v3:Release       


Diagnostics:
  kubernetes:helm.sh/v3:Release (cert-manager-helm):
    error: failed to create chart from template: chart requires kubeVersion: >= 1.21.0-0 which is incompatible with Kubernetes v1.20.0

  pulumi:pulumi:Stack (xxxxx-dev):
    error: Error: invocation of kubernetes:helm:template returned an error: error reading from server: read tcp 127.0.0.1:50939->127.0.0.1:50936: use of closed network connection
        at Object.callback (/Users/xxxx/node_modules/@pulumi/kubernetes/node_modules/@pulumi/runtime/invoke.ts:172:33)
        at Object.onReceiveStatus (/Users/xxx-xx/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/xxx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/xxx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/xxxxx/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

### Steps to reproduce

```typescript
const manager = new certmanager.CertManager("cert-manager", {
    installCRDs: true,
    helmOptions: {
        namespace: namespace.metadata.name,
    },
});

// Create a cluster issuer that uses self-signed certificates.
// This is not very secure, but has the least amount of external
// dependencies, so is simple. Please refer to
// https://cert-manager.io/docs/configuration/selfsigned/
// for additional details on other signing providers.
const issuer = new k8s.apiextensions.CustomResource("issuer", {
    apiVersion: "cert-manager.io/v1",
    kind: "Issuer",
    metadata: {
        name: "selfsigned-issuer",
        namespace: namespace.metadata.name,
    },
    spec: {
        selfSigned: {},
    },
}); 
```

### Expected Behavior

Since my version of kubernetes is higher than the desired one, I expect the error not to occur.

### Actual Behavior

error: failed to create chart from template: chart requires kubeVersion: >= 1.21.0-0 which is incompatible with Kubernetes v1.20.0

Even though my eks-kubernetes version is 1.23.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2023-01-17 16:25
While I did not reproduce the issue, this might have something to do with the version of K8S client linked into the Pulumi provider; we'll try to update to the latest pulumi-kubernetes/sdk and get back to you on this.

**Comment by t0yv0** [comment] 2023-01-23 21:50
Coming back to this, I'm failing to repro with this kubectl/k8s versions. Could you please provide the output of `pulumi about` and `kubectl version --short`?:

```
kubectl version --short                                       
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.25.3
```

The program I'm trying is below. I run `pulumi up` - have to run it twice because the first time it fails with a connection issue, something is not awaiting the creation properly; but the second run succeeds:

```
  kubernetes:cert-manager.io/v1:Issuer (issuer):
    error: resource repro-pulumi-kubernetes-cert-manager-18/selfsigned-issuer was not successfully created by the Kubernetes API server : Inter
nal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-helm-1955d4ec-webhook.
repro-pulumi-kubernetes-cert-manager-18.svc:443/mutate?timeout=10s": dial tcp 10.96.145.199:443: connect: connection refused
```
 
```typescript
import * as certmanager from "@pulumi/kubernetes-cert-manager";
import * as k8s from "@pulumi/kubernetes";

const ns = new k8s.core.v1.Namespace("tempns", {metadata: {
    name: "repro-pulumi-kubernetes-cert-manager-18",
}});

const manager = new certmanager.CertManager("cert-manager", {
    installCRDs: true,
    helmOptions: {
        namespace: ns.metadata.name,
    },
});

// Create a cluster issuer that uses self-signed certificates.
// This is not very secure, but has the least amount of external
// dependencies, so is simple. Please refer to
// https://cert-manager.io/docs/configuration/selfsigned/kube
// for additional details on other signing providers.
const issuer = new k8s.apiextensions.CustomResource("issuer", {
    apiVersion: "cert-manager.io/v1",
    kind: "Issuer",
    metadata: {
        name: "selfsigned-issuer",
        namespace: ns.metadata.name,
    },
    spec: {
        selfSigned: {},
    },
});
```

And `pulumi about`:

```
CLI          
Version      3.52.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME                     VERSION
aws                      5.28.0
docker                   3.6.1
eks                      0.40.0
kubernetes               3.23.1
kubernetes-cert-manager  0.0.5
nodejs                   unknown

Host     
OS       darwin
Version  13.1
Arch     x86_64

This project is written in nodejs: executable='/Users/t0yv0/.nix-profile/bin/node' version='v18.12.1'

Current Stack: t0yv0/repro-pulumi-kubernetes-cert-manager-18/dev

TYPE                                       URN
pulumi:pulumi:Stack                        urn:pulumi:dev::repro-pulumi-kubernetes-cert-manager-18::pulumi:pulumi:Stack::repro-pulumi-kubernetes-cert-manager-18-dev
pulumi:providers:kubernetes                urn:pulumi:dev::repro-pulumi-kubernetes-cert-manager-18::pulumi:providers:kubernetes::default_3_23_1
kubernetes:core/v1:Namespace               urn:pulumi:dev::repro-pulumi-kubernetes-cert-manager-18::kubernetes:core/v1:Namespace::tempns
pulumi:providers:kubernetes-cert-manager   urn:pulumi:dev::repro-pulumi-kubernetes-cert-manager-18::pulumi:providers:kubernetes-cert-manager::default_0_0_5
kubernetes-cert-manager:index:CertManager  urn:pulumi:dev::repro-pulumi-kubernetes-cert-manager-18::kubernetes-cert-manager:index:CertManager::cert-manager
kubernetes:cert-manager.io/v1:Issuer       urn:pulumi:dev::repro-pulumi-kubernetes-cert-manager-18::kubernetes:cert-manager.io/v1:Issuer::issuer
pulumi:providers:kubernetes                urn:pulumi:dev::repro-pulumi-kubernetes-cert-manager-18::pulumi:providers:kubernetes::default
kubernetes:helm.sh/v3:Release              urn:pulumi:dev::repro-pulumi-kubernetes-cert-manager-18::kubernetes-cert-manager:index:CertManager$kubernetes:helm.sh/v3:Release::cert-manager-helm


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi

Dependencies:
NAME                             VERSION
@pulumi/awsx                     0.40.1
@pulumi/eks                      0.40.0
@pulumi/kubernetes-cert-manager  0.0.5
@pulumi/kubernetes               3.23.1
@pulumi/pulumi                   3.52.1
@types/node                      8.10.66
@pulumi/aws                      5.28.0

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/ by default
```

**Comment by EronWright** [comment] 2023-04-24 17:46
I believe that this is fixed in the Pulumi Kubernetes provider:
https://github.com/helm/helm/blob/e63083492b1917b361321ef6951fad08db81d11f/pkg/chartutil/capabilities.go#L32-L49

**Comment by EronWright** [comment] 2023-10-02 16:52
The secondary error seen by @t0yv0 (`selfsigned-issuer was not successfully created`) is solvable by having the issuer depend on the manager.  An `Issuer` cannot be created until the cert-manager is fully deployed (e.g. its webhooks must be fully initialized).

```typescript
const issuer = new k8s.apiextensions.CustomResource("issuer", {
    apiVersion: "cert-manager.io/v1",
    kind: "Issuer",
    metadata: {
        name: "selfsigned-issuer",
        namespace: ns.metadata.name,
    },
    spec: {
        selfSigned: {},
    },
}, { dependsOn: [manager]});
```

I'm closing this issue, @bmetea please reopen if necessary.

**Closed by EronWright** 2023-10-02 16:52 UTC
Labels: kind/bug
